### ISSUE TITLE
Help with Component and Snap Slider

### ISSUE THREAD

**Issue by eyalabadi98** [franfran/react-native-snap-slider#1]
Hello Everybody,

I am using SnapSlider on my project and I'm coming across an issue of setting state.

I have my SnapSlider in one of my pages, but I have a snapSlider component on my components page (copy and pasted from your code)

I am trying to set the state of my value in my page, but cannot figure out how to do it correctly.

My code is as follows:

This is my Component:
`
'use strict';

import React from 'react';
import { Text, View, AppRegistry } from 'react-native';
import  SnapSlider from 'react-native-snap-slider';
import styles from './styles';
import ridepost from './../../pages/PostARide';

var SliderCarSeats = React.createClass({
    propTypes: {
        onChangeSliderValue: React.PropTypes.func,
    },
    sliderOptions: [
        {value: 0, label: '1'},
        {value: 1, label: '2'},
        {value: 2, label: '3'},
        {value: 3, label: '4'},
        {value: 4, label: '5'},
        {value: 5, label: '6'},

    ],
    temp: 'ekam',

    getInitialState() {
        return {
            defaultItem: 2,
        };
    },
    slidingComplete() {
        console.log("slidingComplete");
        console.log("item selected " + this.refs.slider.state.item);
        console.log("value " + this.sliderOptions[this.refs.slider.state.item].value);
        var seatAvailable = this.refs.slider.state.item;
        console.log("set state of child to " + seatAvailable)
       
    },
    checkForChange(){
        this.temp = this.refs.slider.state.item;
    },

    
    
    render: function( props ) {
        //var itemSelected = this.props.items;
        
        return (
             
            <View style={styles.container}>
                <Text style={styles.seatsTitle}> Seats Available </Text>
                 <SnapSlider ref="slider" containerStyle={styles.snapsliderContainer} style={styles.snapslider}
                    itemWrapperStyle={styles.snapsliderItemWrapper}
                    itemStyle={styles.snapsliderItem}
                    items={this.sliderOptions}
                    defaultItem={this.state.defaultItem}
                    onSlidingComplete={this.slidingComplete} />

                    
                    

           
            </View>
        );
    }
});

export default SliderCarSeats;`

This is my Page, where i render my component:
`  <SliderCarSeats  ref="sliderParent" 
  
    value={this.state.seatAvailable}
    onValueChange={(seatAvailable) => this.setState({seatAvailable})}/>`

**Comment by franfran** [comment]
Since your are writing your own component, maybe you better have a correct structure before using other component inside yours.

`
<SliderCarSeats ref="sliderParent" value={this.state.seatAvailable}
onValueChange={(seatAvailable) => this.setState({seatAvailable})}/>
`

It seems it accept two props.  And from your code, you haven't implement the functions to handle them in your own component.

`
propTypes: {
    onValueChange: React.PropTypes.func, //your were using onChangeSliderValue 
    value: React.PropTypes.number,
},
getInitialState() {
    return {
        defaultItem: value,
    };
}
`
