### ISSUE TITLE
Conditional control label position

### ISSUE THREAD

**Issue by issy-li** [franfran/react-native-snap-slider#3]
Hey,

We are using this slider within our project, our main issue is the label of slider is always at the bottom, Can we submit pull request to make it changing with props?

**Comment by franfran** [comment]
Sure, as long as it won't affect the old props.  Maybe new prop e.g. itemPosition?

**Comment by yeknava** [comment]
Checkout my pull request #4 
I added labelPosition props which will show labels on bottom by default, but accept 'top' to show labels on top of slider and empty or none or others to hide label which in my case I don't like to show any labels at all.

**Comment by franfran** [comment]
I have tested it and working fine.
I have to branch it since I wanted to remove the debugging code and update the Example.

You can checkout the new release now.

Thank you very much.
